<?php


/**
 * Implements hook_install().
 */
function custom_module_install()
{
    $role = \Drupal\user\Entity\Role::load('authenticated');

    if ($role) {

        $permissions = \Drupal::config('marvel.permissions')->get();

        if (!empty($permissions)) {
            $role->grantPermissions(array_keys($permissions));
            $role->save();
        }
    }

    \Drupal::service('user.permissions')->reset();
}