<?php

/**
 * Implements hook_theme()
 */
function marvel_theme($existing, $type, $theme, $path)
{
    return [
        'marvel' => [
            'variables' => [
                'data' => NULL
            ],
        ],
        'marvel-favorites-list' => [
            'variables' => [
                'data' => NULL
            ],
        ],
        'marvel-items-list' => [
            'variables' => [
                'data' => NULL
            ],
        ],    
    ];
}