<?php

/**
 * Implements hook_install().
 */
function marvel_install()
{
    _set_permissions();
}

function _set_permissions()
{
    $role = \Drupal\user\Entity\Role::load('authenticated');

    if ($role) {
        $permissions = \Drupal::config('marvel.permissions')->get();

        if (!empty($permissions)) {
            $role->grantPermissions(array_keys($permissions));
            $role->save();
        }
    }
}
